server.port=8085

spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.routes[0].id=account-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.server.webflux.routes[1].id=payment-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/payments/**

spring.main.web-application-type=reactive